### ISSUE TITLE
Add Maemo

### ISSUE THREAD

**Issue by wjt** [dill/lexknowssystems#22]
The Nokia N900 OS was Maemo 5, or Maemo Fremantle if you prefer. (I prefer Fremantle because I had to look up the number while the codename is firmly imprinted in my memory.) Here is a CC screenshot I found in 30 seconds on the Elizabeth Line. https://www.flickr.com/photos/panaggio/4036987071/ The N900 had a hardware keyboard, with arrow keys, and shipped with a terminal emulator and Debian package management so is clearly a computer not a phone.

There were previous Maemo:s. They were all landscape oriented too. N810 had a hardware keyboard and dpkg so again, it's a computer and Lex would know how to use it.

(Fremantle's successor, Meego Harmattan on the N9, was primarily portrait-orientation so doesn't fit the template.)

**Comment by kkarhan** [comment]
Consider [making a fork](https://github.com/dill/lexknowssystems/fork), adding the image named ``Maemo_5.png`` under ``images`` and [making a pull request](https://github.com/dill/lexknowssystems/compare) after you did so? 

I [did so](https://github.com/dill/lexknowssystems/pull/15) [in the past](https://github.com/dill/lexknowssystems/issues/16) and [just recently](https://github.com/dill/lexknowssystems/pull/25)...

This makes it easier for the maintainer @dill to do so.

I hope that helps...

**Comment by wjt** [comment]
Thanks – as it happens I have already done that a number of times, but this has helped by reminding me to do this!
